# Generated by Django 3.2 on 2021-05-25 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='images/%Y%m%d')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('semantic', models.ImageField(blank=True, max_length=255, upload_to='')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未知病人', max_length=255, verbose_name='姓名')),
                ('birth', models.DateTimeField(auto_now_add=True, verbose_name='出生日期')),
                ('sex', models.CharField(choices=[('unknown', '未知性别'), ('m', '男'), ('f', '女')], default='unknown',
                                         max_length=10)),
                ('Image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.cancerimage')),
            ],
        ),
    ]
