# Generated by Django 3.2 on 2021-05-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.DateField(auto_now_add=True, verbose_name='出生日期'),
        ),
    ]
