# Generated by Django 3.2.3 on 2021-05-26 06:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_auto_20210526_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 6, 11, 0, 130343, tzinfo=utc), verbose_name='出生日期'),
        ),
    ]
