# Generated by Django 3.2.3 on 2021-05-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_alter_person_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.DateField(auto_now_add=True, verbose_name='出生日期'),
        ),
    ]
